### ISSUE TITLE
Fix a mistake in the binomial loss formula

### ISSUE THREAD

**Issue by hcho3** [avinashbarnwal/GSOC-2019#5]
https://github.com/avinashbarnwal/GSOC-2019/blob/c7920bf3f87e86532bbc7137c3f3cc06a1b72ff8/BinomialLoss/C%2B%2B/combination.cpp#L8-L11

This is quite inefficient for large N and R. We should cancel out common terms in `n! / ((n-r)! r!)` so that fewer multiplications are needed. See discussion at https://stackoverflow.com/questions/9330915/number-of-combinations-n-choose-r-in-c. Canceling out common terms also help prevent overflows.

@avinashbarnwal @tdhock

**Comment by tdhock** [comment]
wait wait wait

you should NOT be computing the combinations/choose term at all -- it is constant -- that means it can be ignored/removed in the loss computation.

right now you have
```
  cost = -y_obs*y_hat + n_obs*std::log(1+std::exp(y_hat)) - std::log(combination(n_obs,y_obs));
```

it should be (removing all terms that do not depend on y_hat)
```
  cost = -y_obs*y_hat + n_obs*std::log(1+std::exp(y_hat));
```

**Comment by hcho3** [comment]
@tdhock I agree that the combination term is not part of the gradient and the hessian (since differentiation removes constants). However, I think we should keep `std::log(combination(n_obs,y_obs))` in `loss()` function, since the combination term is still part of the log likelihood.

**Comment by tdhock** [comment]
no no no

there is no reason to keep the constant, it just slows things down.

also where did you get that equation for the cost??? see my derivation at the top of https://www.overleaf.com/5585148772jvsvsxdbgpsd for the correct formulas

**Comment by hcho3** [comment]
@tdhock This is the link @avinashbarnwal sent me: https://www.overleaf.com/5585148772jvsvsxdbgpsd

**Comment by tdhock** [comment]
thanks. there is indeed an error in his derivation. the loss should just be a weighted sum of logistic losses. I updated the overleaf with the correct formula.

**Comment by hcho3** [comment]
@tdhock Thanks for finding the error.

**Comment by avinashbarnwal** [comment]
Thanks, Prof. @tdhock and @hcho3, we discussed this formula in the last meeting. I will remove the constant part from the formula.

**Comment by avinashbarnwal** [comment]
I have changed the document.
